[project]
name = "polars-query-dev-complexity"
version = "0.1.0"
description = "A lightweight tool for measuring the **authoring complexity** of Polars LazyFrame queries."
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "polars",
]

[dependency-groups]
tpch = [
    "linetimer",
    "pydantic",
    "pydantic_settings",
]
